# Generated by Django 2.2.16 on 2022-10-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Можно добавить картинку', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
